In [2]:
import json
import pandas as pd
import geopandas as gpd

gdf_2020 = gpd.read_file('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/landvalue_2020_new.geojson')
#gdf_2010 = gdf_2010.rename(columns={'roll_totalvalue': 'roll_totalvalue_2010'})
#gdf_2010.set_index('ain',inplace=True)
gdf_2020

DriverError: data/landvalue_2020_new.geojson: No such file or directory

In [3]:
gdf_2020.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 43872 entries, 0 to 43871
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ain                        43872 non-null  object
 1   situszip                   43869 non-null  object
 2   center_lat                 43872 non-null  object
 3   center_lon                 43872 non-null  object
 4   rollyear                   43872 non-null  object
 5   roll_landvalue             43872 non-null  object
 6   sqftmain                   43872 non-null  object
 7   roll_impbaseyear           43872 non-null  object
 8   propertylocation           43872 non-null  object
 9   usecodedescchar1           43872 non-null  object
 10  effectiveyearbuilt         43872 non-null  object
 11  parcelboundarydescription  43872 non-null  object
 12  roll_landbaseyear          43872 non-null  object
 13  location_1                 43872 non-null  object
 14  OBJECTID_left              43872 non-null  float64
 15  neighborhood               43872 non-null  object
 16  index_right                43872 non-null  int64
 17  OBJECTID_right             43872 non-null  int64
 18  CT20                       43872 non-null  object
 19  LABEL                      43872 non-null  object
 20  ShapeSTArea                43872 non-null  float64
 21  ShapeSTLength              43872 non-null  float64
 22  geometry                   43872 non-null  geometry
dtypes: float64(3), geometry(1), int64(2), object(17)
memory usage: 7.7+ MB

In [4]:
gdf_2020.query('roll_landbaseyear == "2020"').roll_landbaseyear.count()

1069

In [5]:
gdf_2020_sold = gdf_2020[gdf_2020["roll_landbaseyear"] == '2020']
gdf_2020_sold

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,location_1,OBJECTID_left,neighborhood,index_right,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
13,5077021018,90005-1203,34.057099229999999,-118.28590213,2020,825000,3132,2020,2765 FRANCIS AVE LOS ANGELES CA 90005,Residential,...,"{'latitude': '34.05709923', 'needs_recoding': ...",107.0,Westlake,662,663,212202,2122.02,2.222403e+06,6482.090647,POINT (-118.28590 34.05710)
26,5077016004,90005-3932,34.059471479999999,-118.28691623,2020,1980000,0,2020,2904 W 7TH ST LOS ANGELES CA 90005,Commercial,...,"{'latitude': '34.05947148', 'needs_recoding': ...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28692 34.05947)
27,5077028005,90006-1708,34.055649979999998,-118.28719352,2020,1140000,2521,2020,2716 JAMES M WOOD BLVD LOS ANGELES CA 90006,Residential,...,"{'latitude': '34.05564998', 'needs_recoding': ...",107.0,Westlake,662,663,212202,2122.02,2.222403e+06,6482.090647,POINT (-118.28719 34.05565)
37,5077016027,90005,34.05946402,-118.28819145999999,2020,13137160,0,2020,2968 W 7TH ST LOS ANGELES CA 90005,Commercial,...,"{'latitude': '34.05946402', 'needs_recoding': ...",107.0,Westlake,664,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28819 34.05946)
58,5076004026,90006,34.054171220000001,-118.2874051,2020,329400,1220,2020,"940 S ELDEN AVENUE, 108 LOS ANGELES CA 90006",Residential,...,"{'latitude': '34.05417122', 'needs_recoding': ...",107.0,Westlake,684,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28741 34.05417)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43577,5443019018,90026-2015,34.090827640000001,-118.24744742,2020,1012100,1034,2020,2201 VALENTINE ST LOS ANGELES CA 90026,Residential,...,"{'latitude': '34.09082764', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24745 34.09083)
43628,5443030015,90039-3715,34.096897210000002,-118.24995341,2020,890000,1115,2020,1915 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09689721', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24995 34.09690)
43661,5443009006,90026-2055,34.092538300000001,-118.25035086,2020,1040000,958,2020,2217 VESTAL AVE LOS ANGELES CA 90026,Residential,...,"{'latitude': '34.0925383', 'needs_recoding': F...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25035 34.09254)
43725,5443011021,90026-2058,34.093203469999999,-118.2492603,2020,972000,2485,2020,2304 VESTAL AVE LOS ANGELES CA 90026,Residential,...,"{'latitude': '34.09320347', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24926 34.09320)
43747,5443006015,90039-3726,34.095189939999997,-118.25177797000001,2020,520000,713,2020,1938 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,"{'latitude': '34.09518994', 'needs_recoding': ...",27.0,Echo Park,525,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25178 34.09519)

In [6]:
min_number = min(gdf_2020_sold.ain)
print(min_number)

5056001020

In [7]:
max_number = max(gdf_2020_sold.ain)
print(max_number)

5518033003

In [8]:
import requests
import json


url = 'https://data.lacounty.gov/resource/rjze-ndj2.json?$where=within_box(the_geom, 34.1164, -118.3217, 34.01333, -118.2675)&$limit=100000' # copied and pasted from the webpage
r = requests.get(url)
parcel = pd.DataFrame(json.loads(r.text))
parcel

,the_geom,lon_coord,ain,lat_coord,x_coord,y_coord,shape_area,shape_len
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32052234,5052003001,34.02944719,6464550.25589,1833253.40852,4118.85839844,268.710312492
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036613,5052003002,34.0294473,6464597.58649,1833253.29705,4118.71191406,268.700285953
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036544,5052003004,34.02927138,6464597.59358,1833189.27834,5822.9453125,366.020815496
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036271,5052003010,34.02859509,6464597.635,1832943.16,5821.99609375,366.000915114
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036179,5052003012,34.02836261,6464597.645,1832858.555,6561.81738281,376.420914855
...,...,...,...,...,...,...,...,...
52251,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29500987,5540014010,34.09448939,6472349.83528,1856899.75435,17708.1816406,537.983233013
52252,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.2942414,5540015005,34.094516,6472582.52329,1856908.75437,9905.31347656,485.910341354
52253,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29424216,5540016010,34.09423002,6472581.98691,1856804.68404,10059.3476563,487.292871966
52254,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29465601,5540023002,34.09311708,6472455.505,1856400.03,6749.98144531,370.00250984
52255,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.295756,5540026006,34.09132439,6472120.54739,1855748.61818,7204.76464844,388.192655311

In [9]:
parcelgdf = gpd.GeoDataFrame(
    parcel, geometry=gpd.points_from_xy(parcel.lon_coord, parcel.lat_coord, 
                                          crs='EPSG:4326'))
parcelgdf

,the_geom,lon_coord,ain,lat_coord,x_coord,y_coord,shape_area,shape_len,geometry
0,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32052234,5052003001,34.02944719,6464550.25589,1833253.40852,4118.85839844,268.710312492,POINT (-118.32052 34.02945)
1,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036613,5052003002,34.0294473,6464597.58649,1833253.29705,4118.71191406,268.700285953,POINT (-118.32037 34.02945)
2,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036544,5052003004,34.02927138,6464597.59358,1833189.27834,5822.9453125,366.020815496,POINT (-118.32037 34.02927)
3,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036271,5052003010,34.02859509,6464597.635,1832943.16,5821.99609375,366.000915114,POINT (-118.32036 34.02860)
4,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.32036179,5052003012,34.02836261,6464597.645,1832858.555,6561.81738281,376.420914855,POINT (-118.32036 34.02836)
...,...,...,...,...,...,...,...,...,...
52251,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29500987,5540014010,34.09448939,6472349.83528,1856899.75435,17708.1816406,537.983233013,POINT (-118.29501 34.09449)
52252,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.2942414,5540015005,34.094516,6472582.52329,1856908.75437,9905.31347656,485.910341354,POINT (-118.29424 34.09452)
52253,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29424216,5540016010,34.09423002,6472581.98691,1856804.68404,10059.3476563,487.292871966,POINT (-118.29424 34.09423)
52254,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.29465601,5540023002,34.09311708,6472455.505,1856400.03,6749.98144531,370.00250984,POINT (-118.29466 34.09312)
52255,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.295756,5540026006,34.09132439,6472120.54739,1855748.61818,7204.76464844,388.192655311,POINT (-118.29576 34.09132)

In [10]:
gdf_2020_sold = gdf_2020_sold.drop(columns=['index_right'])
gdf_2020_sold

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,roll_landbaseyear,location_1,OBJECTID_left,neighborhood,OBJECTID_right,CT20,LABEL,ShapeSTArea,ShapeSTLength,geometry
13,5077021018,90005-1203,34.057099229999999,-118.28590213,2020,825000,3132,2020,2765 FRANCIS AVE LOS ANGELES CA 90005,Residential,...,2020,"{'latitude': '34.05709923', 'needs_recoding': ...",107.0,Westlake,663,212202,2122.02,2.222403e+06,6482.090647,POINT (-118.28590 34.05710)
26,5077016004,90005-3932,34.059471479999999,-118.28691623,2020,1980000,0,2020,2904 W 7TH ST LOS ANGELES CA 90005,Commercial,...,2020,"{'latitude': '34.05947148', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28692 34.05947)
27,5077028005,90006-1708,34.055649979999998,-118.28719352,2020,1140000,2521,2020,2716 JAMES M WOOD BLVD LOS ANGELES CA 90006,Residential,...,2020,"{'latitude': '34.05564998', 'needs_recoding': ...",107.0,Westlake,663,212202,2122.02,2.222403e+06,6482.090647,POINT (-118.28719 34.05565)
37,5077016027,90005,34.05946402,-118.28819145999999,2020,13137160,0,2020,2968 W 7TH ST LOS ANGELES CA 90005,Commercial,...,2020,"{'latitude': '34.05946402', 'needs_recoding': ...",107.0,Westlake,665,212204,2122.04,2.294673e+06,6149.261568,POINT (-118.28819 34.05946)
58,5076004026,90006,34.054171220000001,-118.2874051,2020,329400,1220,2020,"940 S ELDEN AVENUE, 108 LOS ANGELES CA 90006",Residential,...,2020,"{'latitude': '34.05417122', 'needs_recoding': ...",107.0,Westlake,685,213401,2134.01,2.110769e+06,6327.274225,POINT (-118.28741 34.05417)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43577,5443019018,90026-2015,34.090827640000001,-118.24744742,2020,1012100,1034,2020,2201 VALENTINE ST LOS ANGELES CA 90026,Residential,...,2020,"{'latitude': '34.09082764', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24745 34.09083)
43628,5443030015,90039-3715,34.096897210000002,-118.24995341,2020,890000,1115,2020,1915 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,2020,"{'latitude': '34.09689721', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24995 34.09690)
43661,5443009006,90026-2055,34.092538300000001,-118.25035086,2020,1040000,958,2020,2217 VESTAL AVE LOS ANGELES CA 90026,Residential,...,2020,"{'latitude': '34.0925383', 'needs_recoding': F...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25035 34.09254)
43725,5443011021,90026-2058,34.093203469999999,-118.2492603,2020,972000,2485,2020,2304 VESTAL AVE LOS ANGELES CA 90026,Residential,...,2020,"{'latitude': '34.09320347', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.24926 34.09320)
43747,5443006015,90039-3726,34.095189939999997,-118.25177797000001,2020,520000,713,2020,1938 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,2020,"{'latitude': '34.09518994', 'needs_recoding': ...",27.0,Echo Park,526,197410,1974.10,1.499700e+07,18531.588486,POINT (-118.25178 34.09519)

In [11]:
joinedgdf2020=gpd.sjoin(gdf_2020_sold.to_crs('EPSG:4326'),parcelgdf.to_crs('EPSG:4326'),how='left')
joinedgdf2020

,ain_left,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,geometry,index_right,the_geom,lon_coord,ain_right,lat_coord,x_coord,y_coord,shape_area,shape_len
13,5077021018,90005-1203,34.057099229999999,-118.28590213,2020,825000,3132,2020,2765 FRANCIS AVE LOS ANGELES CA 90005,Residential,...,POINT (-118.28590 34.05710),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,5077016004,90005-3932,34.059471479999999,-118.28691623,2020,1980000,0,2020,2904 W 7TH ST LOS ANGELES CA 90005,Commercial,...,POINT (-118.28692 34.05947),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,5077028005,90006-1708,34.055649979999998,-118.28719352,2020,1140000,2521,2020,2716 JAMES M WOOD BLVD LOS ANGELES CA 90006,Residential,...,POINT (-118.28719 34.05565),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,5077016027,90005,34.05946402,-118.28819145999999,2020,13137160,0,2020,2968 W 7TH ST LOS ANGELES CA 90005,Commercial,...,POINT (-118.28819 34.05946),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,5076004026,90006,34.054171220000001,-118.2874051,2020,329400,1220,2020,"940 S ELDEN AVENUE, 108 LOS ANGELES CA 90006",Residential,...,POINT (-118.28741 34.05417),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43577,5443019018,90026-2015,34.090827640000001,-118.24744742,2020,1012100,1034,2020,2201 VALENTINE ST LOS ANGELES CA 90026,Residential,...,POINT (-118.24745 34.09083),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43628,5443030015,90039-3715,34.096897210000002,-118.24995341,2020,890000,1115,2020,1915 WALCOTT WAY LOS ANGELES CA 90039,Residential,...,POINT (-118.24995 34.09690),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43661,5443009006,90026-2055,34.092538300000001,-118.25035086,2020,1040000,958,2020,2217 VESTAL AVE LOS ANGELES CA 90026,Residential,...,POINT (-118.25035 34.09254),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43725,5443011021,90026-2058,34.093203469999999,-118.2492603,2020,972000,2485,2020,2304 VESTAL AVE LOS ANGELES CA 90026,Residential,...,POINT (-118.24926 34.09320),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43747,5443006015,90039-3726,34.095189939999997,-118.25177797000001,2020,520000,713,2020,1938 WHITMORE AVE LOS ANGELES CA 90039,Residential,...,POINT (-118.25178 34.09519),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
join2020 = gdf_2020_sold.merge(parcelgdf, how='left',on='ain')
join2020 = join2020.dropna()
join2020

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,ShapeSTLength,geometry_x,the_geom,lon_coord,lat_coord,x_coord,y_coord,shape_area,shape_len,geometry_y
0,5077021018,90005-1203,34.057099229999999,-118.28590213,2020,825000,3132,2020,2765 FRANCIS AVE LOS ANGELES CA 90005,Residential,...,6482.090647,POINT (-118.28590 34.05710),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28588994,34.05709437,6475072.26029,1843283.06734,6749.84082031,369.993771822,POINT (-118.28589 34.05709)
1,5077016004,90005-3932,34.059471479999999,-118.28691623,2020,1980000,0,2020,2904 W 7TH ST LOS ANGELES CA 90005,Commercial,...,6149.261568,POINT (-118.28692 34.05947),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28690403,34.05946662,6474767.56137,1844147.24676,9194.07910156,424.855280106,POINT (-118.28690 34.05947)
2,5077028005,90006-1708,34.055649979999998,-118.28719352,2020,1140000,2521,2020,2716 JAMES M WOOD BLVD LOS ANGELES CA 90006,Residential,...,6482.090647,POINT (-118.28719 34.05565),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28718133,34.05564513,6474679.59944,1842756.77662,6770.40820313,370.81451909,POINT (-118.28718 34.05565)
3,5077016027,90005,34.05946402,-118.28819145999999,2020,13137160,0,2020,2968 W 7TH ST LOS ANGELES CA 90005,Commercial,...,6149.261568,POINT (-118.28819 34.05946),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28817926,34.05945916,6474381.30723,1844145.63719,53504.7099609,1007.99025833,POINT (-118.28818 34.05946)
4,5076004026,90006,34.054171220000001,-118.2874051,2020,329400,1220,2020,"940 S ELDEN AVENUE, 108 LOS ANGELES CA 90006",Residential,...,6327.274225,POINT (-118.28741 34.05417),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28739291,34.05416636,6474613.97469,1842218.81047,24653.3447266,631.014501916,POINT (-118.28739 34.05417)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,5402024006,90026-4031,34.073482830000003,-118.26922489,2020,800000,0,2020,517 ROSEMONT AVE LOS ANGELES CA 90026,Residential,...,9761.838870,POINT (-118.26922 34.07348),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26921269,34.07347797,6480139.6577,1849231.40539,7507.69628906,400.13007226,POINT (-118.26921 34.07348)
1009,5402014009,90026-3931,34.078948339999997,-118.27024531000001,2020,882400,1210,2020,1014 N RAMPART BLVD LOS ANGELES CA 90026,Residential,...,7708.360007,POINT (-118.27025 34.07895),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.27023311,34.07894349,6479835.98736,1851221.23303,5584.640625,338.483363825,POINT (-118.27023 34.07894)
1017,5402014020,90026-3926,34.079164919999997,-118.26960808,2020,900000,2596,2020,1033 N CORONADO ST LOS ANGELES CA 90026,Residential,...,7708.360007,POINT (-118.26961 34.07916),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26959589,34.07916007,6480029.15975,1851299.53217,7499.76660156,399.991892436,POINT (-118.26960 34.07916)
1041,5424016027,90026-2323,34.08339591,-118.26783193,2020,1100000,2052,2020,1407 MCCOLLUM ST LOS ANGELES CA 90026,Residential,...,11167.787060,POINT (-118.26783 34.08340),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26781974,34.08339106,6480571.10326,1852837.82668,4798.84570313,319.987066318,POINT (-118.26782 34.08339)
1046,5424016004,90026-2323,34.083286459999997,-118.26790011,2020,1140200,2728,2020,1401 MCCOLLUM ST LOS ANGELES CA 90026,Residential,...,11167.787060,POINT (-118.26790 34.08329),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26788791,34.0832816,6480550.355,1852798.05,5969.02539063,339.497340718,POINT (-118.26789 34.08328)

In [13]:
join2020.query('neighborhood == "Westlake"').neighborhood.count()

119

In [14]:
join2020['shape_area'] = pd.to_numeric(join2020['shape_area'])
join2020['roll_landvalue'] = pd.to_numeric(join2020['roll_landvalue'])

In [15]:
join2020['landvalue_sqft']=join2020['roll_landvalue']/join2020['shape_area']
join2020

,ain,situszip,center_lat,center_lon,rollyear,roll_landvalue,sqftmain,roll_impbaseyear,propertylocation,usecodedescchar1,...,geometry_x,the_geom,lon_coord,lat_coord,x_coord,y_coord,shape_area,shape_len,geometry_y,landvalue_sqft
0,5077021018,90005-1203,34.057099229999999,-118.28590213,2020,825000,3132,2020,2765 FRANCIS AVE LOS ANGELES CA 90005,Residential,...,POINT (-118.28590 34.05710),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28588994,34.05709437,6475072.26029,1843283.06734,6749.840820,369.993771822,POINT (-118.28589 34.05709),122.225105
1,5077016004,90005-3932,34.059471479999999,-118.28691623,2020,1980000,0,2020,2904 W 7TH ST LOS ANGELES CA 90005,Commercial,...,POINT (-118.28692 34.05947),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28690403,34.05946662,6474767.56137,1844147.24676,9194.079102,424.855280106,POINT (-118.28690 34.05947),215.355989
2,5077028005,90006-1708,34.055649979999998,-118.28719352,2020,1140000,2521,2020,2716 JAMES M WOOD BLVD LOS ANGELES CA 90006,Residential,...,POINT (-118.28719 34.05565),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28718133,34.05564513,6474679.59944,1842756.77662,6770.408203,370.81451909,POINT (-118.28718 34.05565),168.379803
3,5077016027,90005,34.05946402,-118.28819145999999,2020,13137160,0,2020,2968 W 7TH ST LOS ANGELES CA 90005,Commercial,...,POINT (-118.28819 34.05946),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28817926,34.05945916,6474381.30723,1844145.63719,53504.709961,1007.99025833,POINT (-118.28818 34.05946),245.532777
4,5076004026,90006,34.054171220000001,-118.2874051,2020,329400,1220,2020,"940 S ELDEN AVENUE, 108 LOS ANGELES CA 90006",Residential,...,POINT (-118.28741 34.05417),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.28739291,34.05416636,6474613.97469,1842218.81047,24653.344727,631.014501916,POINT (-118.28739 34.05417),13.361270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,5402024006,90026-4031,34.073482830000003,-118.26922489,2020,800000,0,2020,517 ROSEMONT AVE LOS ANGELES CA 90026,Residential,...,POINT (-118.26922 34.07348),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26921269,34.07347797,6480139.6577,1849231.40539,7507.696289,400.13007226,POINT (-118.26921 34.07348),106.557321
1009,5402014009,90026-3931,34.078948339999997,-118.27024531000001,2020,882400,1210,2020,1014 N RAMPART BLVD LOS ANGELES CA 90026,Residential,...,POINT (-118.27025 34.07895),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.27023311,34.07894349,6479835.98736,1851221.23303,5584.640625,338.483363825,POINT (-118.27023 34.07894),158.004796
1017,5402014020,90026-3926,34.079164919999997,-118.26960808,2020,900000,2596,2020,1033 N CORONADO ST LOS ANGELES CA 90026,Residential,...,POINT (-118.26961 34.07916),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26959589,34.07916007,6480029.15975,1851299.53217,7499.766602,399.991892436,POINT (-118.26960 34.07916),120.003734
1041,5424016027,90026-2323,34.08339591,-118.26783193,2020,1100000,2052,2020,1407 MCCOLLUM ST LOS ANGELES CA 90026,Residential,...,POINT (-118.26783 34.08340),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26781974,34.08339106,6480571.10326,1852837.82668,4798.845703,319.987066318,POINT (-118.26782 34.08339),229.221790
1046,5424016004,90026-2323,34.083286459999997,-118.26790011,2020,1140200,2728,2020,1401 MCCOLLUM ST LOS ANGELES CA 90026,Residential,...,POINT (-118.26790 34.08329),"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",-118.26788791,34.0832816,6480550.355,1852798.05,5969.025391,339.497340718,POINT (-118.26789 34.08328),191.019459

In [16]:
censusjoin2020 = join2020.groupby('CT20').ain.count()
censusjoin2020

CT20
188201     4
195100    26
195400    25
195500     4
195600     2
          ..
224010     4
224200     2
224310     4
224320     1
224410     1
Name: ain, Length: 82, dtype: int64

In [17]:
df_census_n = pd.DataFrame(censusjoin2020)
df_census_n =df_census_n.rename(columns={'ain': 'n_parcel'})
df_census_n

        n_parcel
CT20
188201         4
195100        26
195400        25
195500         4
195600         2
...          ...
224010         4
224200         2
224310         4
224320         1
224410         1

[82 rows x 1 columns]

In [18]:
censuslvsfjoin2020 = join2020.groupby('CT20').landvalue_sqft.sum()
censuslvsfjoin2020

CT20
188201     437.394742
195100    4434.585512
195400    4095.360087
195500     989.321295
195600     420.241248
             ...
224010    2316.198873
224200     214.985409
224310     446.980258
224320     103.208982
224410     116.962755
Name: landvalue_sqft, Length: 82, dtype: float64

In [19]:
df_lvsf = pd.DataFrame(censuslvsfjoin2020)
df_lvsf

        landvalue_sqft
CT20
188201      437.394742
195100     4434.585512
195400     4095.360087
195500      989.321295
195600      420.241248
...                ...
224010     2316.198873
224200      214.985409
224310      446.980258
224320      103.208982
224410      116.962755

[82 rows x 1 columns]

In [20]:
df_lvsf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 82 entries, 188201 to 224410
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   landvalue_sqft  82 non-null     float64
dtypes: float64(1)
memory usage: 3.3+ KB

In [21]:
df_census_n.info()

<class 'pandas.core.frame.DataFrame'>
Index: 82 entries, 188201 to 224410
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   n_parcel  82 non-null     int64
dtypes: int64(1)
memory usage: 3.3+ KB

In [22]:
newjoin = df_lvsf.merge(df_census_n, how='left',on='CT20')
newjoin

        landvalue_sqft  n_parcel
CT20
188201      437.394742         4
195100     4434.585512        26
195400     4095.360087        25
195500      989.321295         4
195600      420.241248         2
...                ...       ...
224010     2316.198873         4
224200      214.985409         2
224310      446.980258         4
224320      103.208982         1
224410      116.962755         1

[82 rows x 2 columns]

In [23]:
newjoin['avgprice_tract']=newjoin['landvalue_sqft']/newjoin['n_parcel']
newjoin

        landvalue_sqft  n_parcel  avgprice_tract
CT20
188201      437.394742         4      109.348685
195100     4434.585512        26      170.560981
195400     4095.360087        25      163.814403
195500      989.321295         4      247.330324
195600      420.241248         2      210.120624
...                ...       ...             ...
224010     2316.198873         4      579.049718
224200      214.985409         2      107.492704
224310      446.980258         4      111.745065
224320      103.208982         1      103.208982
224410      116.962755         1      116.962755

[82 rows x 3 columns]

In [26]:
#newjoin.to_file('avgprice_tract_2020.geojson', driver='GeoJSON')

newjoin.to_csv('/Users/pearlliu100/Documents/GitHub/UDS-Project--Full-Team-/avgprice_tract_2020.csv', index = True)